Add Slime Ball max code
ChroniclerCherry/stardew-valley-mods pull request #99
Opened 2024-12-16 22:00 UTC by bsavage81

Adds code to increase the max slime balls per day, along with a GMCM menu.

2025-01-12 05:43 UTC, Pathoschild requested changes
Thanks for the pull request! I added a few comments inline to discuss.

2025-01-12 05:43 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
Won't this result in the max limit being additive to the vanilla limit? For example, let's say you have 20 slimes, which would normally produce 4 slime balls. If you set the max slime balls to 6, that would spawn up to 10 slime balls per day (6 from the patch and 4 from the vanilla code).

2025-01-12 05:43 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +            ? Math.Min(slimeBasedLimit, _config.MaxDailySlimeBalls)
It's probably confusing that the max slime balls is still limited to the number of water troughs, since most players won't have a custom slime hutch map. Even if they set the max slime balls to 100, it'll still be limited to 4 since there's only 4 water troughs.

2025-01-12 05:43 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +#pragma warning restore AvoidNetField // Avoid Netcode types when possible
We can set `slimeBall.Fragility = 2` instead to avoid the net field warning.

2025-01-12 05:43 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +    private void SetupGMCM()
Could you split the Generic Mod Config Menu integration into a separate PR? That way it can be reviewed/tweaked/merged separately while we discuss the slime ball changes.

2025-01-12 16:41 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +            ? Math.Min(slimeBasedLimit, _config.MaxDailySlimeBalls)
This is following the vanilla logic that the troughs need to be watered in order for slime balls to appear. If you have 100 slime, and only 1 trough watered, it will register 25 slimes and divide that by 5 to get you 5 slime balls. If all 4 troughs are watered, you will register all 100/5 resulting in 25 slime balls. Basically the code maintains the vanilla reasoning of 25% for each watered trough.

2025-01-13 02:27 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
As far as I can tell it doesn't do this. I have been playing with it for a few weeks now and I am pretty sure it is not additive

2025-01-13 02:27 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +#pragma warning restore AvoidNetField // Avoid Netcode types when possible
Implemented

2025-01-13 02:33 UTC, bsavage81 reviewed
I don't use Github much, so not sure how to split a PR into two. Let me know if you see any other issues.

2025-01-17 00:26 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
In a prefix patch, [`return true` means the original method should run too](https://harmony.pardeike.net/articles/patching-prefix.html#changing-the-result-and-skipping-the-original). So this patch spawns the desired number of slimes, then it runs the vanilla method which spawns slimes again.

2025-01-17 00:27 UTC, Pathoschild commented on ChangeSlimeHutchLimit/ModEntry.cs
> +    private void SetupGMCM()
Done via PR #100.

2025-01-17 00:29 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
Ok, so should we switch it to a postfix?

2025-01-17 00:42 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
or am I overthinking it, and I should just return false

2025-01-21 02:43 UTC, bsavage81 commented on ChangeSlimeHutchLimit/ModEntry.cs
> +        return true;
Went ahead and updated the code to be additive to the vanilla method

2025-01-23 21:20 UTC, bsavage81 commented
Closed in favor of changes in [PR 106](https://github.com/ChroniclerCherry/stardew-valley-mods/pull/106)

2025-01-23 21:20 UTC, closed without merging